# these are the defaults, you should override them in your projects config/app.yml file
#all:
#  extjs_gen_plugin:
#    theme:            aero    # Extjs library theme
#    adapter:          ext     # Extjs Adapter Type jquery, prototype, yui, or ext
#    date_format:      'm/d/Y' # The default date formatting

#    list_max_per_page:     20
#    list_tabbed:           true   # If the gridpanel is being added to a tab panel there will be no header config
#    list_trackMouseOver:   true   # See Extjs GridPanel config docs
#    list_loadMask:         true   # See Extjs GridPanel config docs
#    list_stripeRows:       true   # See Extjs GridPanel config docs
#    list_forceFit:         false  # See Extjs GridPanel config docs

    # True uses a viewport with a border layout.  By default tabpanel and filterpanel are regions under viewport
    # Set to false if you want to use your own layout.  See module_init_app_partial.
#    module_returns_layout:   true

    # The name of a javascript partial file located in the app/templates directory that utilizes the generated tabpanel,
    # filterpanel, or gridpanel modules in your custom layout.
    # Only used if module_returns_layout: false
    # Example file name is _init_app.js.php
#    module_init_app_partial: init_app

    # the global var name for the list tabpanel.  By default gridpanel is an item of the tabpanel
#    module_tabpanel_name:    Ext.app.sf.TabPanel

    # the global var name for the list gridpanel
#    module_gridpanel_name:   Ext.app.sf.GridPanel

    # the global var name for the list filterpanel.
#    module_filterpanel_name: Ext.app.sf.FilterPanel

#    export_boolean_as_string: false      # export booleans as a string
#    export_boolean_true:      'True'    # exported booleans true will be string True
#    export_boolean_false:     'False'   # exported booleans false will be string False
#    export_date_format:       false     # exported date format.  Use a symfony date string like 'MM/dd/yy' or false for no formating

#    remote_combo_limit:     50  # max number of remote combo results to return when combobox is editable
#    remote_combo_pageSize:  0   # number of records to show when paging.  Value greater than 0 turns paging on
#    remote_combo_minChars:  3   # minimum number of characters to type before querying when combobox is editable
